import type { Metadata } from "next";
import Header from "@/shared/header";
import Footer from "@/shared/footer";
import "./globals.css";
import "../style/index.css";

export const metadata: Metadata = {
  title: "Anza Capital Investment",
  description: "Generated by Anza Capital Investment",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
